Milestone 6
arslanbisharat/ror-social-scaffold pull request #3
Opened 2020-06-23 13:04 UTC by arslanbisharat

### Friendship tables
>_In this milestone, implement friendships with 2 rows for mutual friendship_

### I completed this project alone

2020-06-23 14:08 UTC, euqueme requested changes
### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @arslanbisharat :lollipop: 

### Thank you for your submission :handshake: your project works very well :ok_hand: I think you understood the concepts of what it needed to be accomplished in this project and you achieve it with ease :medal_sports:  there are some changes to make in your code to make it more efficient and also follow good programming practices.

#### Milestone 6: Friendships v2 specs

* [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created

```ruby
# FriendRequest model

def confirm_friend
  self.update_attributes(confirmed: true)
  FriendRequest.create!(friend_id: self.user_id,
                  user_id: self.friend_id,
                  confirmed: true)
end
```
* [ ] thanks to this, we can find user friends only by user_id in friendships table

```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "FriendRequest"
has_many :friends, through: :confirmed_friendships
```
- Even though you are handling this differently, let's take advantage of creating 2 rows for friendships so the relationship can be accomplished with Rails Associations instead of using multiple methods that are memory consuming

* [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "FriendRequest", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
* [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "FriendRequest", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
#### Views & Helpers

* [ ] There should be NO application logic in the views nor helpers (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers.
* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- Please use helper methods and / or partials to put if/else statements instead of putting them straight in the view, the views where I found if or if/else statements are the following:
  - app/views/users/index.html.erb
  - app/views/users/show.html.erb
  - app/views/post/index.html.erb

### That's it! :raised_hands: 

### Please :pray:  do the changes :technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-06-23 16:07 UTC, arslanbisharat commented
Almost my written code for previous milestones had to update. Please Have a look for that too.
Thank You

2020-06-23 19:26 UTC, uche-inyama requested changes
## Changes Required

Hi team :wave: 

When I accepted a friend request from a user, in the records, two rows were not created.

Use this image as a reference, it is a snapshot of my rails console, after I accepted a friend request on the front end.

![Screenshot from 2020-06-23 20-19-34](https://user-images.githubusercontent.com/46329537/85449196-65238980-b58f-11ea-8ff0-c4d02f779f80.png)

Use the information my colleague, Maru(TSE),  provided as a guide.
```ruby
# User model

has_many :confirmed_friendships, -> { where confirmed: true }, class_name: "FriendRequest"
has_many :friends, through: :confirmed_friendships
```
- Even though you are handling this differently, let's take advantage of creating 2 rows for friendships so the relationship can be accomplished with Rails Associations instead of using multiple methods that are memory consuming

* [ ] User#pending_friends can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who needs to confirm friendship
has_many :pending_friendships, -> { where confirmed: false }, class_name: "FriendRequest", foreign_key: "user_id"
has_many :pending_friends, through: :pending_friendships, source: :friend
```
* [ ] User#friend_requests can be defined as association with SQL query instead of processing objects in application memory (as the database was created to store and query data it is always more efficient than ruby)

```ruby
# User model

# Users who requested to be friends (needed for notifications)
has_many :inverted_friendships, -> { where confirmed: false }, class_name: "FriendRequest", foreign_key: "friend_id"
has_many :friend_requests, through: :inverted_friendships
```
#### Views & Helpers

* [ ] There should be NO application logic in the views nor helpers (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers.
* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [ ] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- Please use helper methods and / or partials to put if/else statements instead of putting them straight in the view, the views where I found if or if/else statements are the following:
  - app/views/users/index.html.erb
  - app/views/users/show.html.erb
  - app/views/post/index.html.erb

After making the changes submit another form for a code review. 


#### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

2020-06-24 02:14 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @arslanbisharat :balloon: 

### Thank you for working on the requested changes :muscle:  I see you've created a new entity to take care of the inverse_friendships so you are making use of Rails Associations to load the information faster :sparkles: . Please make the following changes

#### Behaviour

- [ ] I had problems executing your project because of this migration CreateFriendRequests < ActiveRecord::Migration[6.0] version, change it to have the same version as your other migrations ([5.2])

#### Test cases

- [ ] 40 of your test cases are failing so let's make the corrections:

```
authenticate a user
  login a user (FAILED - 1)
  logout a user (FAILED - 2)
  sign up a user (FAILED - 3)

LikesController
  liking and disliking a post
    dislikes a post (FAILED - 4)
    likes a post (FAILED - 5)

friend request
  Accept a friend request (FAILED - 6)
  Decline a friend request (FAILED - 7)
  send a friend request (FAILED - 8)

Logged in user can see other users:
  User is able to see selected user page with their name and posts (FAILED - 9)

UsersController
  GET #index
    gets all the users and render index page (FAILED - 10)
  GET #show
    gives the user show page (FAILED - 11)

Like
  creating valid comment (FAILED - 12)

UserFriendship
  is not valid without user_id (FAILED - 13)
  is not valid without friend_id (FAILED - 14)
  is valid with all of the correct fields (FAILED - 15)
  is valid if the status is one from: requested, confirmed, declined, cancelled (FAILED - 16)
  is not valid if the status is different from: requested, confirmed, declined, cancelled (FAILED - 17)
  is not valid if the requested friend doesnt exist (FAILED - 18)
  Associations
    example at ./spec/models/user_friendship_spec.rb:49 (FAILED - 19)
    example at ./spec/models/user_friendship_spec.rb:48 (FAILED - 20)
  Validations
    example at ./spec/models/user_friendship_spec.rb:45 (FAILED - 21)
    example at ./spec/models/user_friendship_spec.rb:43 (FAILED - 22)
    example at ./spec/models/user_friendship_spec.rb:42 (FAILED - 23)
    example at ./spec/models/user_friendship_spec.rb:44 (FAILED - 24)

PostsController
  POST #create
    valid params
      creates a new post (FAILED - 25)
    invalid params
      redirects to index page with invalid params (FAILED - 26)
  GET #index
    gets all the user posts and render index page (FAILED - 27)

Post
  show all posts (FAILED - 28)
  creating valid posts (FAILED - 29)

Logged in user can send/receive/acept/decline friendship invitations/requests:
  User is able to accept his friend requests pending response (FAILED - 30)
  User is able to see his friend requests pending response (FAILED - 31)
  User is able to send friendship invitations from All Users page (FAILED - 32)
  User is able to decline his friend requests pending response (FAILED - 33)

FriendRequestsController
  friendship features
    accepts a friend request (FAILED - 34)
    unfriends an already friend (FAILED - 35)
    rejects a friend request (FAILED - 36)
    creates a friend request (FAILED - 37)

Comment
  creating valid comment (FAILED - 38)

CommentsController
  creating comments
    creates a new post with valid params (FAILED - 39)
    renders new template with invalid params (FAILED - 40)
```

#### Views & Helpers

* [ ] There should be NO application logic in the views nor helpers (no `Post.new`, `Comment.create`, `current_user.friends.find_by(...)`...). Everything connected with data processing should be encapsulated in models and used in controllers.
* [ ] View-related logic can be encapsulated in View helpers (app/helpers/\*_helper.rb)
* [x] There shoud be absolutely NO logic in views.

  > Views are only for displaying information that became available to it from its corresponding controller not generating it. **Resources**
* [Where Do I Put My Code?](http://codefol.io/posts/Where-Do-I-Put-My-Code)
* [The Beginner's Guide to Rails Helpers](https://mixandgo.com/learn/the-beginners-guide-to-rails-helpers)
* [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/no_logic_in_helpers_requirement.png) from Pathwright

- Please use helper methods and/or partials to put if/else statements instead of putting them straight in the view, I've left comments on your code where this change has to be applied

### That's it! :raised_hands: 

### Please :pray:  do the changes :technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

2020-06-24 02:14 UTC, euqueme commented on app/views/users/index.html.erb
> +        <% end %>
- [ ] use a helper method to put the if/else statement and render the links within the helper instead of having the logic in the view

2020-06-24 04:29 UTC, euqueme approved these changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @arslanbisharat :balloon: 

### You've done an amazing job with this project, thank you for doing all the requested changes, your project is professional and meets all the required criteria, Congratulations you may merge this branch :tada: :tada: :tada: 

### Keep up the good work :clinking_glasses: 

PROJECT STATUS: APPROVED :heavy_check_mark:

2020-06-24 04:31 UTC, merged